### ISSUE TITLE
No such export error.

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [FinalZFivem/FinalZ-Fishing#1]
```
[   2709172] [b3095_GTAProce]             MainThrd/ error during NUI callback useItem: @ox_inventory/modules/items/shared.lua:3: No such export StartFishing in resource Z_Fishing
[   2715797] [b3095_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @ox_inventory/modules/items/shared.lua:3: No such export StartFishing in resource Z_Fishing^7
```

Script is started after ox_inventory. I will see about adding `exports { 'StartFishing' }` to manifest and see if that fixes it.

**Comment by Goshawk1337** [comment]
Hi i don't know what could be the issue, since for me and the tester team it worked fine. You are used our Premade Items from the docs? Please join our discord, so we can discuss further.
